import npsjournal from "./assets/projects/npsjournal.png";
import moviedb from "./assets/projects/moviedb.png";
import btfsite from "./assets/projects/btfsite.png";
import portiko from "./assets/projects/portiko.png";
import enzian from "./assets/projects/enzian.png";
import cookbook from "./assets/projects/cookbook.png";

export const codeProjects = [
  {
    id: 0,
    title: "National Park Service Journal",
    description:
      "This is a full-stack application that allows users to browse NPS parks and create a list with journal entries for each.",
    image: npsjournal,
    link: "https://nps-journal-372a1876b1c6.herokuapp.com/",
  },
  {
    id: 1,
    title: "Movie Database Website",
    description:
      "I was the project leader for this group project that lets users search for movie information and view trending movies via external APIs.",
    image: moviedb,
    link: "https://renabmew.github.io/com6338-10-10-bauer-brown-colver/",
  },
  {
    id: 2,
    title: "Back to the Future Fansite",
    description:
      "I was the project leader for this group project that pays homage the fantastic Back to the Future Trilogy!",
    image: btfsite,
    link: "https://renabmew.github.io/BacktotheFuture/",
  },
];

export const designProjects = [
  {
    id: 0,
    title: "Portiko Brand Identity and Logo Design",
    description:
      "This was a logo and brand identity design for a mobile technology company. Created with Illustrator and Photoshop.",
    image: portiko,
    link: "./assets/projects/PortikoBrand.pdf",
  },
  {
    id: 1,
    title: "Enzian Theater Brochure",
    description:
      "This was an information brochure created for a local nonprofit. Created with InDesign.",
    image: enzian,
    link: "./assets/projects/EnzianBrochure.pdf",
  },
  {
    id: 2,
    title: "Handbook for the Recently Risen",
    description:
      "This was a cookbook featuring breakfast foods. Created with InDesign with images generated by Bing.",
    image: cookbook,
    link: "./assets/projects/Cookbook.pdf",
  },
];
